### PR TITLE
new docs and bugfixes from juliacon

### PR DESCRIPTION
**Pull request by tiemvanderdeure**

### CODE REVIEW

**Comment by rafaqz** [comment]
Also see some of the recent changes to DimensionalData.jl vitepress by @lazarusA

Fixes to add doc version dropdown, links that aren't broken etc
https://github.com/rafaqz/DimensionalData.jl/pull/804
https://github.com/rafaqz/DimensionalData.jl/pull/744
https://github.com/rafaqz/DimensionalData.jl/pull/746

**Comment by tiemvanderdeure** [comment]
Yea still trying to figure it out. I looked at the Rasters docs also but maybe DD is the better example. Also I can't get the docs to build locally on my laptop, but I don't know if that's because something is off in this repo or on my setup (I'm on windows which isn't ideal)

**Comment by lazarusA** [comment]
DD should build locally. I did all my tests that way. If not, please report back.

**Comment by lazarusA** [comment]
Also, this migth help for doing local builds.

https://juliadatacubes.github.io/YAXArrays.jl/stable/development/contribute.html#Build-docs-locally

**Comment by tiemvanderdeure** [comment]
Thanks for chipping in @lazarusA!

From the preview generated by the check it seems it at least kind of worked:
https://tiemvanderdeure.github.io/SpeciesDistributionModels.jl/previews/PR11/

> Also, this migth help for doing local builds.
> 
> https://juliadatacubes.github.io/YAXArrays.jl/stable/development/contribute.html#Build-docs-locally

I did this, but get a `Warning: Documenter could not auto-detect the building environment. Skipping deployment.` and the locally generated page shows a (vitepress-themed) 404 error.

**Comment by rafaqz** [comment]
@tiemvanderdeure yes DD is the better example, I still need to add some of those changes to Rasters

**Comment by tiemvanderdeure** [comment]
@rafaqz or @lazarusA could you help me understand what went wrong here? The documentation doesn't really give any error so that doesn't say much - I also just added some text to a .md file so I can't see what I possibly could have broken? 

I tried to build locally and it gets stuck on `ExpandTemplates: expanding markdown templates`, which I can find lots of issues about but not any clear solution to.

**Comment by lazarusA** [comment]
I would guess that is the data download. Is it working?

**Comment by tiemvanderdeure** [comment]
Okay it wasn't quite that but it put me on the right path, thanks!

**Pull request merged**
